name: check-change-scope
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**/*.txt"

jobs:
  check:
    name: Check changes are in one module
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check modified files are in one module
        id: check_files
        run: ./.github/scripts/check_scope_of_changes.sh --pr_number ${{ github.event.number }}
        shell: bash
  call-pre-commit-workflow:
    uses: ./.github/workflows/pre-commit.yaml
